apiVersion: apps/v1
kind: Deployment
metadata:
 name: sdt-deployment
 namespace: sdt
spec:
 replicas: 3
 selector:
   matchLabels:
     app: sdt
 template:
   metadata:
     labels:
       app: sdt
   spec:
     containers:
     - name: sdt
       image: gcr.io/repcore-prod/sdt:e1d11e4a-5fe5-47c6-9f42-505e9dcf55d7
       ports:
       - containerPort: 11000
