apiVersion: apps/v1
kind: Deployment
metadata:
 name: sdt-deployment
 namespace: sdt
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sdt
 template:
   metadata:
     labels:
       app: sdt
   spec:
     terminationGracePeriodSeconds: 5
     containers:
     - name: sdt
       image: gcr.io/sask-dev-talks/sdt:73acb3ba-b209-4ca3-bad6-867fd627219a
       ports:
       - containerPort: 11000
       livenessProbe:
        httpGet:
          path: /healthz
          port: 11000
        initialDelaySeconds: 3
        periodSeconds: 3
       readinessProbe:
        httpGet:
          path: /healthz
          port: 11000
        initialDelaySeconds: 3
        periodSeconds: 3
       resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
