apiVersion: apps/v1
kind: Deployment
metadata:
 name: sdt-deployment
 namespace: sdt
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sdt
 template:
   metadata:
     labels:
       app: sdt
   spec:
     containers:
     - name: sdt
       image: gcr.io/sask-dev-talks/sdt:1c56f766-2aff-4624-a74f-798abdfd6a0d
       ports:
       - containerPort: 11000
