apiVersion: apps/v1
kind: Deployment
metadata:
 name: fortio
 namespace: sdt
spec:
 replicas: 1
 selector:
   matchLabels:
     app: fortio
 template:
   metadata:
     labels:
       app: fortio
   spec:
     containers:
     - name: fortio
       image: istio/fortio